--
-- PostgreSQL database dump
--

-- Dumped from database version 15.6 (Debian 15.6-1.pgdg120+2)
-- Dumped by pg_dump version 15.4

-- Started on 2024-10-05 09:17:09 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 33635)
-- Name: categories; Type: TABLE; Schema: public; Owner: storeusr
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    categoryname character varying(255),
    categorystatus integer
);


ALTER TABLE public.categories OWNER TO storeusr;

--
-- TOC entry 214 (class 1259 OID 33634)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: storeusr
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 33683)
-- Name: invalidated_tokens; Type: TABLE; Schema: public; Owner: storeusr
--

CREATE TABLE public.invalidated_tokens (
    id bigint NOT NULL,
    expiration_time timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL
);


ALTER TABLE public.invalidated_tokens OWNER TO storeusr;

--
-- TOC entry 223 (class 1259 OID 33682)
-- Name: invalidated_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: storeusr
--

ALTER TABLE public.invalidated_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invalidated_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 33641)
-- Name: products; Type: TABLE; Schema: public; Owner: storeusr
--

CREATE TABLE public.products (
    id integer NOT NULL,
    categoryid integer,
    createddate timestamp(6) without time zone,
    modifieddate timestamp(6) without time zone,
    productname character varying(255),
    productpicture character varying(255),
    unitinstock integer,
    unitprice numeric(10,2)
);


ALTER TABLE public.products OWNER TO storeusr;

--
-- TOC entry 216 (class 1259 OID 33640)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: storeusr
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 33649)
-- Name: roles; Type: TABLE; Schema: public; Owner: storeusr
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    role_name character varying(255) NOT NULL,
    CONSTRAINT roles_role_name_check CHECK (((role_name)::text = ANY ((ARRAY['USER'::character varying, 'MANAGER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.roles OWNER TO storeusr;

--
-- TOC entry 218 (class 1259 OID 33648)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: storeusr
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 33655)
-- Name: user_roles; Type: TABLE; Schema: public; Owner: storeusr
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO storeusr;

--
-- TOC entry 222 (class 1259 OID 33659)
-- Name: users; Type: TABLE; Schema: public; Owner: storeusr
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO storeusr;

--
-- TOC entry 221 (class 1259 OID 33658)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: storeusr
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3385 (class 0 OID 33635)
-- Dependencies: 215
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: storeusr
--

COPY public.categories (id, categoryname, categorystatus) FROM stdin;
2	Tablet	1
3	Smart Watch	1
4	Laptop	1
1	Smart Phone	1
\.


--
-- TOC entry 3389 (class 0 OID 33649)
-- Dependencies: 219
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: storeusr
--

COPY public.roles (id, role_name) FROM stdin;
1	USER
2	MANAGER
3	ADMIN
\.


--
-- TOC entry 3400 (class 0 OID 0)
-- Dependencies: 214
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: storeusr
--

SELECT pg_catalog.setval('public.categories_id_seq', 6, true);


--
-- TOC entry 3401 (class 0 OID 0)
-- Dependencies: 223
-- Name: invalidated_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: storeusr
--

SELECT pg_catalog.setval('public.invalidated_tokens_id_seq', 1, true);


--
-- TOC entry 3402 (class 0 OID 0)
-- Dependencies: 216
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: storeusr
--

SELECT pg_catalog.setval('public.products_id_seq', 9, true);


--
-- TOC entry 3403 (class 0 OID 0)
-- Dependencies: 218
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: storeusr
--

SELECT pg_catalog.setval('public.roles_id_seq', 4, true);


--
-- TOC entry 3404 (class 0 OID 0)
-- Dependencies: 221
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: storeusr
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- TOC entry 3225 (class 2606 OID 33639)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: storeusr
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 3239 (class 2606 OID 33687)
-- Name: invalidated_tokens invalidated_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: storeusr
--

ALTER TABLE ONLY public.invalidated_tokens
    ADD CONSTRAINT invalidated_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 3227 (class 2606 OID 33647)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: storeusr
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 3229 (class 2606 OID 33654)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: storeusr
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 3233 (class 2606 OID 33669)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: storeusr
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 3231 (class 2606 OID 33667)
-- Name: roles uk716hgxp60ym1lifrdgp67xt5k; Type: CONSTRAINT; Schema: public; Owner: storeusr
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uk716hgxp60ym1lifrdgp67xt5k UNIQUE (role_name);


--
-- TOC entry 3235 (class 2606 OID 33671)
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: storeusr
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- TOC entry 3237 (class 2606 OID 33665)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: storeusr
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3240 (class 2606 OID 33672)
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: storeusr
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- TOC entry 3241 (class 2606 OID 33677)
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: storeusr
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2024-10-05 09:17:09 UTC

--
-- PostgreSQL database dump complete
--

